quotes = {"Soggy Sig is when you drop your smoke in a puddle": "Flames",
          "One of my mom's cats is a complete and total slut": "Dragon",
          "So if Flames is in our hearts, does that mean we have heart burn?": "Nathan",
          "I return to the superb owl": "Surv",
          "I diagnose Psych with gay.": "Dom",
          "I dont do meth, thank you": "Diamond",
          "Foot fetishests rejoice": "Flames",
          "who needs opposable thumbs when you have a fucking electric current running through you": "Surv",
          "i love being a horrible influence masked behind the facade of a semi-decent human being": "Sig",
          "i probably shouldnt open this chat in my dining hall huh": "Sig",
          "What is this light hentai shit?": "Diamond",
          "My boy documents are sacred. No girl has ever touched them.": "Dom",
          "Hecc": "Hecc",
          "I think that's illegal in... everywhere, really.": "Tallow",
          "More like FlamesOnFurry": "Tallow",
          "Get out of my yanky danky face fuck off will ya?": "Ama",
          "I regret this place": "Odd",
          "Noo, not the sandy vagina pit": "Diamond"}
