quotes = {"Soggy Sig is when you drop your smoke in a puddle": "Flames",
          "One of my mom's cats is a complete and total slut": "Dragon",
          "So if Flames is in our hearts, does that mean we have heart burn?": "Nathan",
          "I return to the superb owl": "Surv",
          "I diagnose Psych with gay.": "Dom",
          "I dont do meth, thank you": "Diamond",
          "Foot fetishests rejoice": "Flames",
          "who needs opposable thumbs when you have a fucking electric current running through you": "Surv",
          "i love being a horrible influence masked behind the facade of a semi-decent human being": "Sig",
          "i probably shouldnt open this chat in my dining hall huh": "Sig",
          "What is this light hentai shit?": "Diamond",
          "My boy documents are sacred. No girl has ever touched them.": "Dom",
          "Hecc": "Hecc",
          "I think that's illegal in... everywhere, really.": "Tallow",
          "More like FlamesOnFurry": "Tallow",
          "Get out of my yanky danky face fuck off will ya?": "Ama",
          "I regret this place": "Odd",
          "Noo, not the sandy vagina pit": "Diamond",
          "If Jake Paul can do it you can do it": "Flames",
          "Lmoa Constrictor": "Flames",
          "Don't try and test my fapping abilities": "Bounty",
          'I mean everyone is into "the fuck"': "Frogger",
          "Do you legitimately believe the United States of America runs frog carpet bombing tests": "Ace",
          "The bigger the eraser, the bigger the pleasure": "Odd",
          "dad stop yelling at me I'm doing my best": "Gary",
          "I, too, am gay as fuck": "Sig",
          "Gary was born from sig's homosexuality with flames": "Odd",
          "I'd kill myself if I was a Cell alt": "Diamond",
          "Oh boy the ramens": "Dragon",
          "Gary is my child and he must be protected": "Sig",
          "Oof": "Everyone, tbh",
          "IF HECC WAS ICE CREAM SHE'D BE AN ICE CREAM TSUNDERE": "Flames",
          "This is all heccs fault somehow.": "Flames",
          "I prefer the triple-dogdere": "Tallow",
          "dying is unhealthy for the brain": "Mango",
          "we need this server to overload with gay": "Sig",
          "oh my god i can speak": "Gary",
          "The trick is to just not rp. That way nobody can hurt you.": "Tallow",
          "what the fuck": "Coco",
          "can I be in your robot too": "Coco",
          "D-did they just “:p” me.": "Mawile"}
